module : multiclass_classifier.multiclass_classifier.MultiClassClassification
model : mnist_ex1.ClassificationMNIST
dataset : MNIST.MNIST
out_features : 10
num_workers : 0
batch_size : 400
log_every_n_steps : 1
learning_rate : 0.00007
min_epochs : 150
max_epochs : 150
early_stopping_metric : val_acc
data_root: .
run_test : true
fast_dev_run: true
# data_root :
