# MODULE GROUP
module : multiclass_classifier.multiclass_classifier_X3D.MultiClassClassification

# MODEL GROUP
model : x3d_custom.X3D_MOMA
input_crop_size: 312
input_clip_length: 16
model_num_class: 16
depth_factor: 5
aact_out_class :  52 # 52 *16  atomical activities+ nan class x number of frames
subact_out_class : 68 # 68 subactivities
activity_out_class : 17 # 17 activities
pretrained : True
input_channels : 3
x3d_type : x3d_l
checkpoint : /home/nicolasg/moma/checkpoints/x3d_l.pyth
# DATASET GROUP
dataset : MOMA.MOMA
data_root: 'not used'
df_train_path: '/home/nicolasg/code/annotations/train1.csv'
df_val_path: '/home/nicolasg/code/annotations/valid1.csv'

# TRAINER GROUP
#trainer config
overfit_batches : 0.0
num_workers : 10
learning_rate : 0.001
batch_size : 1
log_every_n_steps : 1
num_sanity_val_steps : 0
min_epochs : 150
max_epochs : 150
check_val_every_n_epoch : 1
save_top_k : 1
early_stopping_metric : val_acc
gpus : [6]
#logging and GPUs config all on default see utils.configargparse
# run_test : true
# fast_dev_run: true

